owner: soehlert
repo: upptime
user-agent: UpptimeBot
sites:
  - name: Soehlert
    url: https://www.soehlert.com
  - name: SamOehlert
    url: https://www.samoehlert.com
assignees:
  - soehlert
status-website:
  cname: status.soehlert.com
  logoUrl: https://raw.githubusercontent.com/koj-co/upptime/79d9d1c22ecf706acc51f17798d7c7dbc710ab40/assets/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Monitoring for my own personal websites using (Upptime)[https://github.com/koj-co/upptime] 
